kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: otel
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "127.0.0.1"
    protocol: TCP
